//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5120_Quality_Education_in_Australia_Iteration_01.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FIT5120_Quality_Education_in_Australia_Iteration_01_dbEntities : DbContext
    {
        public FIT5120_Quality_Education_in_Australia_Iteration_01_dbEntities()
            : base("name=FIT5120_Quality_Education_in_Australia_Iteration_01_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EnglishSupport> EnglishSupports { get; set; }
        public virtual DbSet<TraditionalFestival> TraditionalFestivals { get; set; }
    }
}
