//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5120_Quality_Education_in_Australia_Iteration_01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TraditionalFestival
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ShortInfo { get; set; }
        public string DetailInformation { get; set; }
        public string Image01 { get; set; }
        public string Image02 { get; set; }
        public string Date { get; set; }
    }
}
